services:
  - type: web
    name: asistente-reuniones
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT --server.enableCORS=false"
    envVars:
      - key: PORT
        value: 10000
